name: PDK Tests

on: pull_request

jobs:
  run-pdk-tests:
    name: Run PDK tests
    runs-on: ubuntu-latest
    container:
      image: puppet/pdk:latest
    defaults:
      run:
        working-directory: site/profile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run PDK version
        run: pdk --version

      - name: Run PDK validate
        run: |
          echo "results=${{github.workspace}}/site/profile/pdk_validate_results.txt" >> $GITHUB_ENV
          pdk validate --format=text:pdk_validate_results.txt
        continue-on-error: true

      - name: Annotate PR with PDK validation results
        run: |
          .github/scripts/annotate.sh "$results" true
        working-directory: ${{ github.workspace }}

      - name: Run PDK unit test
        run: pdk test unit

        continue-on-error: true
